edit buildspec

diff --git a/ci/buildspec.yaml b/ci/buildspec.yaml
--- a/ci/buildspec.yaml
+++ b/ci/buildspec.yaml
@@ -15,5 +15,26 @@ phases:
       - sam build
   post_build:
     commands:
-      - source ./ci/set_envs.sh
-      - sam deploy --parameter-overrides $CLOUDFORMATION_PARAMETER_OVERRIDES --stack-name=sam-app-$ENV --config-file ./ci/samconfig.toml --region=us-east-1
+      - |
+        cd ci
+        if [ -z "$ENV" ]; then
+          echo "Error: ENV environment variable not set"
+          exit 1
+        fi
+
+        env_file=".env.$ENV"
+
+        if [ ! -f "$env_file" ]; then
+          echo "Error: $env_file not found"
+          exit 1
+        fi
+
+        parameter_overrides="--parameter-overrides"
+
+        while IFS='=' read -r key value || [[ -n "$key" ]]; do
+          parameter_overrides+=" $key=$value"
+        done < "$env_file"
+
+        echo "Running 'sam deploy' command with parameter overrides:"
+        echo "$parameter_overrides"
+        sam deploy --parameter-overrides $parameter_overrides --stack-name=sam-app-$ENV --config-file ./ci/samconfig.toml --region=us-east-1
